@shop.manoel.hostAddress = http://localhost:5001

POST {{shop.manoel.hostAddress}}/tasks/
Accept: application/json
Content-Type: application/json
{
  "id": 0,
  "titulo": "TESTE 1",
  "descricao": "TESTE 1",
  "data": "2024-09-26T13:22:38.473Z",
  "status": 0
}
###

PUT {{shop.manoel.hostAddress}}/tasks/
Accept: application/json
Content-Type: application/json
{
  "id": 15,
  "titulo": "TESTE 1",
  "descricao": "TESTE 1",
  "data": "2024-09-26T13:22:38.473Z",
  "status": 0
}
###

GET {{shop.manoel.hostAddress}}/tasks/14
Accept: application/json

###

GET {{shop.manoel.hostAddress}}/todos/1
Accept: application/json

###
